# Generated by Django 3.0.8 on 2020-08-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('published_date', models.DecimalField(decimal_places=0, max_digits=4)),
                ('authors', models.CharField(max_length=255)),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ratings_count', models.PositiveIntegerField()),
                ('thumbnail_link', models.URLField()),
            ],
        ),
    ]
