# Generated by Django 3.0.8 on 2020-08-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200801_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
