# Generated by Django 3.0.8 on 2020-08-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200802_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='thumbnail_link',
            new_name='thumbnail',
        ),
    ]
